### ISSUE TITLE
Unreliable startup

### ISSUE THREAD

**Issue by thejpster** [Neotron-Compute/Neotron-Pico-BIOS#49]
When flashing the RP2040 with `probe-run` I observe a couple of different outcomes:

## Start-up beeps

1. You get all the start-up beeps
2. You get some of the beeps (often every other beep), and some errors:

```text
WARN  Error executing Request { request_type: ShortWriteAlt, register: 114, length_or_data: 116, crc: 243 }: Decoding Error BadResponseResult [0, 0]
└─ neotron_pico_bios::{impl#1}::bmc_do_request @ src/main.rs:933
WARN  Error executing Request { request_type: ShortWriteAlt, register: 114, length_or_data: 97, crc: 152 }: Decoding Error BadResponseResult [0, 0]
└─ neotron_pico_bios::{impl#1}::bmc_do_request @ src/main.rs:933
```

You seem to be able to trigger case (2) by using `DEFMT_LOG=info`. My default of `DEFMT_LOG=debug` gets you case (1).

## Keyboard

1. Usually the keyboard does not work. The BIOS enters "power_idle" and never comes out.
2. Sometimes it starts up and prints an infinite number of "Interrupts: 0b00000000" messages.
3. Doing a Reset usually makes the keyboard work, but there's no defmt logs.

**Comment by jonathanpallant** [comment]
I suppose that after an RP2040 debug reset, the reset of the PCB has not been reset, including the MCP23S17. So maybe that needs to be put into a reset start on start-up.

**Comment by jonathanpallant** [comment]
Replacing `wfi` with 1,000,000 nops makes everything work again. The the issue is probably setting up the SIO and/or NVIC to generate interrupts when the IRQ input changes.

I have a Picoscope capture where the IRQ input to the RP2040 goes low and nothing happens.

**Comment by jannic** [comment]
Does it work reliably after a power cycle? I'm suspecting that the reset done after flashing only resets parts of the chip.

**Comment by thejpster** [comment]
So I forgot to enable interrupts. And it was wfe not wfi, so that mattered.
